baseURL = 'https://ignissolarisstudio.com/jadedu/'
title = 'JadeDu'
theme = 'PaperMod'
defaultContentLanguage = 'zh'
defaultContentLanguageInSubdir = false
enableEmoji = true
enableRobotsTXT = true

[languages.zh]
label = '中文'
locale = 'zh-cn'
weight = 1
title = 'JadeDu'

[languages.zh.params]
languageAltTitle = '中文'
description = 'Jade Du — Ignis Solaris Studio 开发者'

[languages.zh.params.profileMode]
subtitle = 'Ignis Solaris Studio 开发者 | 心理学背景 & QA 老将'

[[languages.zh.menu.main]]
name = '关于'
url = '/about/'
weight = 10

[[languages.zh.menu.main]]
name = '项目'
url = '/project/'
weight = 20

[[languages.zh.menu.main]]
name = '博客'
url = '/posts/'
weight = 30

[[languages.zh.menu.main]]
name = '简历'
url = '/resume/'
weight = 40

[[languages.zh.menu.main]]
name = 'IgnisSolarisStudio'
url = 'https://ignissolarisstudio.com/'
weight = 50

[languages.en]
label = 'EN'
locale = 'en'
weight = 2
title = 'JadeDu'

[languages.en.params]
languageAltTitle = 'EN'
description = 'Jade Du — Dev @ Ignis Solaris Studio'

[languages.en.params.profileMode]
subtitle = 'Dev @ Ignis Solaris Studio | Psychology-driven & QA veteran.'

[[languages.en.menu.main]]
name = 'About'
url = '/about/'
weight = 10

[[languages.en.menu.main]]
name = 'Project'
url = '/project/'
weight = 20

[[languages.en.menu.main]]
name = 'Blogs'
url = '/posts/'
weight = 30

[[languages.en.menu.main]]
name = 'Resume'
url = '/resume/'
weight = 40

[[languages.en.menu.main]]
name = 'IgnisSolarisStudio'
url = 'https://ignissolarisstudio.com/'
weight = 50

[languages.fr]
label = 'FR'
locale = 'fr'
weight = 3
title = 'JadeDu'

[languages.fr.params]
languageAltTitle = 'FR'
description = 'Jade Du — Développeuse @ Ignis Solaris Studio'

[languages.fr.params.profileMode]
subtitle = 'Dév. @ Ignis Solaris Studio | Psychologie & vétéran QA.'

[[languages.fr.menu.main]]
name = 'À propos'
url = '/about/'
weight = 10

[[languages.fr.menu.main]]
name = 'Projets'
url = '/project/'
weight = 20

[[languages.fr.menu.main]]
name = 'Blogues'
url = '/posts/'
weight = 30

[[languages.fr.menu.main]]
name = 'CV'
url = '/resume/'
weight = 40

[[languages.fr.menu.main]]
name = 'IgnisSolarisStudio'
url = 'https://ignissolarisstudio.com/'
weight = 50

[params]
env = 'production'
author = 'Jade Du'
defaultTheme = 'auto'
displayFullLangName = true
ShowReadingTime = true
ShowShareButtons = true
ShowPostNavLinks = true

[params.profileMode]
enabled = true
title = 'Jade Du'
imageUrl = 'avatar.PNG'
imageTitle = 'Jade Du'
imageWidth = 150
imageHeight = 150

[[params.socialIcons]]
name = 'github'
title = 'GitHub'
url = 'https://github.com/Tinangelle'

[[params.socialIcons]]
name = 'linkedin'
title = 'LinkedIn'
url = 'https://www.linkedin.com/in/xundu/'

[[params.socialIcons]]
name = 'discord'
title = 'Discord'
url = 'https://discord.com/users/552717578271850496'

[[params.socialIcons]]
name = 'email'
title = 'Email'
url = 'mailto:jadedu026@gmail.com'

[markup.goldmark.renderer]
unsafe = true
